services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.6
    volumes:
      - './unbound.conf:/opt/unbound/etc/unbound/unbound.conf'
    restart: unless-stopped

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: eth1
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.4/31
